### ISSUE TITLE
Could you please publish 3.0.8 version

### ISSUE THREAD

**Issue by glebmachine** [sius/swagger-nodegen-cli#4]
That will be great!

**Comment by sius** [comment]
Thank you for the reminder, I will publish it until tomorrow

**Comment by glebmachine** [comment]
Will be great, thanks)
-- 
Gleb Mikheev
CTO

*Beta*
Bersenevsky Lane 5 Building 1

Mobile:  +7 (916) 118-28-21
Telegram: https://t.me/glebmikheev
Facebook: https://www.facebook.com/glebmachine

www.betaagency.ru
https://www.facebook.com/beta.moscow/

**Comment by sius** [comment]
A new version has been published **swagger-nodegen-cli@3.0.8**
Please note that the current swagger-codegen-cli-3.0.8.jar version supports fewer languages ​​than the older versions (2.x.x):

Available languages: [aspnetcore, csharp, csharp-dotnet2,
 dynamic-html,html, html2, java, jaxrs-cxf-client, jaxrs-cxf,
 inflector, jaxrs-cxf-cdi, jaxrs-spec, jaxrs-jersey, jaxrs-di,
 jaxrs-resteasy-eap, jaxrs-resteasy, spring, nodejs-server,
 openapi, openapi-yaml, kotlin-client, kotlin-server, php,
 python, scala, scala-akka-http-server, swift3, swift4,
 typescript-angular]

**Comment by glebmachine** [comment]
Thanks!

**Comment by glebmachine** [comment]
Thanks!
