### ISSUE TITLE
DefaultService.js being generated within controllers folder instead of service folder

### ISSUE THREAD

**Issue by rulrok** [sius/swagger-nodegen-cli#5]
My root project `package.json`:

```json
{
  "name": "fake-api",
  "version": "1.0.0",
  "description": "Fake API for development",
  "scripts": {
    "generate": "swagger-codegen-cli generate -l nodejs-server -i openapi.yaml -o ./fake-api"
  },
  "license": "Unlicense",
  "private": true,
  "dependencies": {},
  "devDependencies": {
    "swagger-nodegen-cli": "^3.0.8"
  }
}

```

It generates what I need inside `fake-api` folder, but this happens:

![image](https://user-images.githubusercontent.com/3097987/78027855-71070300-7334-11ea-9730-01df680cfba1.png)

The generated controller references the service file which was wrongly put inside the controllers folder

![image](https://user-images.githubusercontent.com/3097987/78027904-8419d300-7334-11ea-9b61-b17d220a377f.png)

**Comment by sius** [comment]
As far as I can see this error only occurs under Windows.

Updated to 3.0.19
