### ISSUE TITLE
 ModuleWithProviders requires 1 type argument with Angular 10

### ISSUE THREAD

**Issue by stbnvll** [sius/swagger-nodegen-cli#8]
Hi,

I use `swagger-nodegen-cli` to generate some services defined by Swagger 2.0 in my Angular frontend. Since the update to Angular 10 the generated `ApiModule` needs a type argument, otherwise the following error appears when compiling: "Generic type 'ModuleWithProviders<T>' requires 1 type argument(s)." Can this problem be solved by configuration?

Thanks for your help.

**Comment by sius** [comment]
Unfortunately not, swagger-nodegen-cli only wraps the java library swagger-codegen-cli.jar. Maybe a newer version of this library fixes the problem. Currently version 3.0.19 is used.
To display the detailed config options use:
sc config-help -l typescript-angular

**Comment by dolanmiu** [comment]
@sius Could you push an update soon?

Swagger codegen cli has fixed the issue:

https://github.com/swagger-api/swagger-codegen/issues/10417

**Comment by dolanmiu** [comment]
@sius @stbnvll 

I have made a PR to fix this issue:

https://github.com/sius/swagger-nodegen-cli/pull/11
